# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Dec 05 17:26:10 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 701)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.bsp_select_combobox = QtGui.QComboBox(self.groupBox_2)
        self.bsp_select_combobox.setObjectName("bsp_select_combobox")
        self.gridLayout.addWidget(self.bsp_select_combobox, 0, 1, 1, 1)
        self.bsp_enumerate_button = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsp_enumerate_button.sizePolicy().hasHeightForWidth())
        self.bsp_enumerate_button.setSizePolicy(sizePolicy)
        self.bsp_enumerate_button.setObjectName("bsp_enumerate_button")
        self.gridLayout.addWidget(self.bsp_enumerate_button, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.memory_init_lineedit = QtGui.QLineEdit(self.groupBox_2)
        self.memory_init_lineedit.setObjectName("memory_init_lineedit")
        self.gridLayout.addWidget(self.memory_init_lineedit, 1, 1, 1, 1)
        self.memory_init_browse_button = QtGui.QPushButton(self.groupBox_2)
        self.memory_init_browse_button.setObjectName("memory_init_browse_button")
        self.gridLayout.addWidget(self.memory_init_browse_button, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.ram_kernel_binary_lineedit = QtGui.QLineEdit(self.groupBox_2)
        self.ram_kernel_binary_lineedit.setObjectName("ram_kernel_binary_lineedit")
        self.gridLayout.addWidget(self.ram_kernel_binary_lineedit, 2, 1, 1, 1)
        self.ram_kernel_browse_button = QtGui.QPushButton(self.groupBox_2)
        self.ram_kernel_browse_button.setObjectName("ram_kernel_browse_button")
        self.gridLayout.addWidget(self.ram_kernel_browse_button, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.ram_kernel_origin_lineedit = QtGui.QLineEdit(self.groupBox_2)
        self.ram_kernel_origin_lineedit.setObjectName("ram_kernel_origin_lineedit")
        self.gridLayout.addWidget(self.ram_kernel_origin_lineedit, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 3)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.binary_file_lineedit = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binary_file_lineedit.sizePolicy().hasHeightForWidth())
        self.binary_file_lineedit.setSizePolicy(sizePolicy)
        self.binary_file_lineedit.setObjectName("binary_file_lineedit")
        self.gridLayout_2.addWidget(self.binary_file_lineedit, 0, 0, 1, 2)
        self.binary_file_table_remove_button = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binary_file_table_remove_button.sizePolicy().hasHeightForWidth())
        self.binary_file_table_remove_button.setSizePolicy(sizePolicy)
        self.binary_file_table_remove_button.setObjectName("binary_file_table_remove_button")
        self.gridLayout_2.addWidget(self.binary_file_table_remove_button, 3, 1, 1, 2)
        self.binary_file_table_add_button = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binary_file_table_add_button.sizePolicy().hasHeightForWidth())
        self.binary_file_table_add_button.setSizePolicy(sizePolicy)
        self.binary_file_table_add_button.setObjectName("binary_file_table_add_button")
        self.gridLayout_2.addWidget(self.binary_file_table_add_button, 3, 0, 1, 1)
        self.binary_file_browse_button = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binary_file_browse_button.sizePolicy().hasHeightForWidth())
        self.binary_file_browse_button.setSizePolicy(sizePolicy)
        self.binary_file_browse_button.setObjectName("binary_file_browse_button")
        self.gridLayout_2.addWidget(self.binary_file_browse_button, 0, 2, 1, 1)
        self.binary_file_history_tableview = QtGui.QTableView(self.groupBox_6)
        self.binary_file_history_tableview.setObjectName("binary_file_history_tableview")
        self.gridLayout_2.addWidget(self.binary_file_history_tableview, 2, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 0, 1, 3)
        self.operation_progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.operation_progress_bar.setProperty("value", 0)
        self.operation_progress_bar.setObjectName("operation_progress_bar")
        self.gridLayout_3.addWidget(self.operation_progress_bar, 3, 0, 1, 1)
        self.show_log_button = QtGui.QPushButton(self.centralwidget)
        self.show_log_button.setObjectName("show_log_button")
        self.gridLayout_3.addWidget(self.show_log_button, 3, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.program_radio_button = QtGui.QRadioButton(self.groupBox_5)
        self.program_radio_button.setObjectName("program_radio_button")
        self.verticalLayout_7.addWidget(self.program_radio_button)
        self.verify_radio_button = QtGui.QRadioButton(self.groupBox_5)
        self.verify_radio_button.setObjectName("verify_radio_button")
        self.verticalLayout_7.addWidget(self.verify_radio_button)
        self.dump_radio_button = QtGui.QRadioButton(self.groupBox_5)
        self.dump_radio_button.setObjectName("dump_radio_button")
        self.verticalLayout_7.addWidget(self.dump_radio_button)
        self.erase_radio_button = QtGui.QRadioButton(self.groupBox_5)
        self.erase_radio_button.setObjectName("erase_radio_button")
        self.verticalLayout_7.addWidget(self.erase_radio_button)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.flash_lba_checkbox = QtGui.QCheckBox(self.groupBox_4)
        self.flash_lba_checkbox.setObjectName("flash_lba_checkbox")
        self.verticalLayout_6.addWidget(self.flash_lba_checkbox)
        self.flash_bbt_checkbox = QtGui.QCheckBox(self.groupBox_4)
        self.flash_bbt_checkbox.setObjectName("flash_bbt_checkbox")
        self.verticalLayout_6.addWidget(self.flash_bbt_checkbox)
        self.flash_swap_bi_checkbox = QtGui.QCheckBox(self.groupBox_4)
        self.flash_swap_bi_checkbox.setObjectName("flash_swap_bi_checkbox")
        self.verticalLayout_6.addWidget(self.flash_swap_bi_checkbox)
        self.flash_interleave_checkbox = QtGui.QCheckBox(self.groupBox_4)
        self.flash_interleave_checkbox.setObjectName("flash_interleave_checkbox")
        self.verticalLayout_6.addWidget(self.flash_interleave_checkbox)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.operation_address_lineedit = QtGui.QLineEdit(self.groupBox_7)
        self.operation_address_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.operation_address_lineedit.setObjectName("operation_address_lineedit")
        self.gridLayout_5.addWidget(self.operation_address_lineedit, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.operation_length_lineedit = QtGui.QLineEdit(self.groupBox_7)
        self.operation_length_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.operation_length_lineedit.setObjectName("operation_length_lineedit")
        self.gridLayout_5.addWidget(self.operation_length_lineedit, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_7, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setCursor(QtCore.Qt.ArrowCursor)
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_10 = QtGui.QGroupBox(self.tab)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtGui.QLabel(self.groupBox_10)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.memory_operation_address_lineedit = QtGui.QLineEdit(self.groupBox_10)
        self.memory_operation_address_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.memory_operation_address_lineedit.setObjectName("memory_operation_address_lineedit")
        self.gridLayout_6.addWidget(self.memory_operation_address_lineedit, 0, 1, 1, 1)
        self.memory_operation_length_lineedit = QtGui.QLineEdit(self.groupBox_10)
        self.memory_operation_length_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.memory_operation_length_lineedit.setObjectName("memory_operation_length_lineedit")
        self.gridLayout_6.addWidget(self.memory_operation_length_lineedit, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_10)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_10, 1, 0, 1, 2)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ram_write_file_radio_button = QtGui.QRadioButton(self.groupBox_8)
        self.ram_write_file_radio_button.setObjectName("ram_write_file_radio_button")
        self.verticalLayout_8.addWidget(self.ram_write_file_radio_button)
        self.ram_execute_app_radio_button = QtGui.QRadioButton(self.groupBox_8)
        self.ram_execute_app_radio_button.setObjectName("ram_execute_app_radio_button")
        self.verticalLayout_8.addWidget(self.ram_execute_app_radio_button)
        self.ram_memory_test_button = QtGui.QRadioButton(self.groupBox_8)
        self.ram_memory_test_button.setObjectName("ram_memory_test_button")
        self.verticalLayout_8.addWidget(self.ram_memory_test_button)
        self.gridLayout_7.addWidget(self.groupBox_8, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 2, 0, 1, 3)
        self.go_button = QtGui.QPushButton(self.centralwidget)
        self.go_button.setObjectName("go_button")
        self.gridLayout_3.addWidget(self.go_button, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menuFile.addAction(self.action_exit)
        self.menu_Help.addAction(self.action_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MX Toolkit UI", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Board Support Package Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "BSP Name", None, QtGui.QApplication.UnicodeUTF8))
        self.bsp_enumerate_button.setText(QtGui.QApplication.translate("MainWindow", "Enumerate", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Memory init file", None, QtGui.QApplication.UnicodeUTF8))
        self.memory_init_browse_button.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "RAM kernel binary", None, QtGui.QApplication.UnicodeUTF8))
        self.ram_kernel_browse_button.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "RAM kernel origin", None, QtGui.QApplication.UnicodeUTF8))
        self.ram_kernel_origin_lineedit.setText(QtGui.QApplication.translate("MainWindow", "0x80000000", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Binary File Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.binary_file_table_remove_button.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.binary_file_table_add_button.setText(QtGui.QApplication.translate("MainWindow", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.binary_file_browse_button.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.show_log_button.setText(QtGui.QApplication.translate("MainWindow", "Show Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.program_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.verify_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Verify", None, QtGui.QApplication.UnicodeUTF8))
        self.dump_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.erase_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Flash driver options", None, QtGui.QApplication.UnicodeUTF8))
        self.flash_lba_checkbox.setText(QtGui.QApplication.translate("MainWindow", "LBA", None, QtGui.QApplication.UnicodeUTF8))
        self.flash_bbt_checkbox.setText(QtGui.QApplication.translate("MainWindow", "BBT", None, QtGui.QApplication.UnicodeUTF8))
        self.flash_swap_bi_checkbox.setText(QtGui.QApplication.translate("MainWindow", "Swap BI", None, QtGui.QApplication.UnicodeUTF8))
        self.flash_interleave_checkbox.setText(QtGui.QApplication.translate("MainWindow", "Interleave", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Address settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Length (bytes)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Flash Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Address settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Start address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Test length (bytes)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.ram_write_file_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Write file to memory", None, QtGui.QApplication.UnicodeUTF8))
        self.ram_execute_app_radio_button.setText(QtGui.QApplication.translate("MainWindow", "Write application and execute", None, QtGui.QApplication.UnicodeUTF8))
        self.ram_memory_test_button.setText(QtGui.QApplication.translate("MainWindow", "Memory test", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "RAM Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.go_button.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("MainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))

