# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyatk.ui'
#
# Created: Sun Feb 17 10:37:16 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 765)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setCursor(QtCore.Qt.ArrowCursor)
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.mbrowser_pp_write_value = QtGui.QLineEdit(self.groupBox_2)
        self.mbrowser_pp_write_value.setObjectName("mbrowser_pp_write_value")
        self.gridLayout.addWidget(self.mbrowser_pp_write_value, 1, 2, 1, 2)
        self.mbrowser_pp_table = QtGui.QTableView(self.groupBox_2)
        self.mbrowser_pp_table.setObjectName("mbrowser_pp_table")
        self.gridLayout.addWidget(self.mbrowser_pp_table, 2, 0, 1, 4)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.mbrowser_pp_datasize = QtGui.QComboBox(self.groupBox_2)
        self.mbrowser_pp_datasize.setObjectName("mbrowser_pp_datasize")
        self.gridLayout.addWidget(self.mbrowser_pp_datasize, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.mbrowser_pp_address = QtGui.QLineEdit(self.groupBox_2)
        self.mbrowser_pp_address.setObjectName("mbrowser_pp_address")
        self.gridLayout.addWidget(self.mbrowser_pp_address, 1, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mbrowser_browse_save_button = QtGui.QPushButton(self.groupBox_5)
        self.mbrowser_browse_save_button.setObjectName("mbrowser_browse_save_button")
        self.gridLayout_2.addWidget(self.mbrowser_browse_save_button, 4, 1, 1, 2)
        self.mbrowser_browse_datasize = QtGui.QComboBox(self.groupBox_5)
        self.mbrowser_browse_datasize.setObjectName("mbrowser_browse_datasize")
        self.gridLayout_2.addWidget(self.mbrowser_browse_datasize, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 2)
        self.mbrowser_browse_dump_button = QtGui.QPushButton(self.groupBox_5)
        self.mbrowser_browse_dump_button.setObjectName("mbrowser_browse_dump_button")
        self.gridLayout_2.addWidget(self.mbrowser_browse_dump_button, 4, 3, 1, 1)
        self.mbrowser_browse_readlength = QtGui.QSpinBox(self.groupBox_5)
        self.mbrowser_browse_readlength.setMaximum(128)
        self.mbrowser_browse_readlength.setProperty("value", 128)
        self.mbrowser_browse_readlength.setObjectName("mbrowser_browse_readlength")
        self.gridLayout_2.addWidget(self.mbrowser_browse_readlength, 1, 2, 1, 2)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.mbrowser_browse_address = QtGui.QLineEdit(self.groupBox_5)
        self.mbrowser_browse_address.setObjectName("mbrowser_browse_address")
        self.gridLayout_2.addWidget(self.mbrowser_browse_address, 1, 0, 1, 1)
        self.mbrowser_browse_dump_table = QtGui.QTableView(self.groupBox_5)
        self.mbrowser_browse_dump_table.setObjectName("mbrowser_browse_dump_table")
        self.gridLayout_2.addWidget(self.mbrowser_browse_dump_table, 3, 0, 1, 4)
        self.gridLayout.addWidget(self.groupBox_5, 4, 0, 1, 4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.app_browser_tree = QtGui.QTreeView(self.dockWidgetContents_2)
        self.app_browser_tree.setObjectName("app_browser_tree")
        self.verticalLayout_5.addWidget(self.app_browser_tree)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dev_select_combo = QtGui.QComboBox(self.groupBox_3)
        self.dev_select_combo.setObjectName("dev_select_combo")
        self.verticalLayout_3.addWidget(self.dev_select_combo)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dev_select_bsp_list = QtGui.QListView(self.groupBox)
        self.dev_select_bsp_list.setObjectName("dev_select_bsp_list")
        self.verticalLayout.addWidget(self.dev_select_bsp_list)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.action_Open_binary_file = QtGui.QAction(MainWindow)
        self.action_Open_binary_file.setObjectName("action_Open_binary_file")
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionView_log = QtGui.QAction(MainWindow)
        self.actionView_log.setObjectName("actionView_log")
        self.menuFile.addAction(self.action_Open_binary_file)
        self.menuFile.addAction(self.actionView_log)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyATK i.MX Bootstrap Kit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Bootstrap Application", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Peek/Poke Device Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Data size", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Memory address", None, QtGui.QApplication.UnicodeUTF8))
        self.mbrowser_pp_address.setText(QtGui.QApplication.translate("MainWindow", "0x00000000", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "P&eek", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "P&oke", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Write value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Device Memory Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.mbrowser_browse_save_button.setText(QtGui.QApplication.translate("MainWindow", "&Save to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Data size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Read length", None, QtGui.QApplication.UnicodeUTF8))
        self.mbrowser_browse_dump_button.setText(QtGui.QApplication.translate("MainWindow", "&Dump memory", None, QtGui.QApplication.UnicodeUTF8))
        self.mbrowser_browse_readlength.setSuffix(QtGui.QApplication.translate("MainWindow", " bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Memory address", None, QtGui.QApplication.UnicodeUTF8))
        self.mbrowser_browse_address.setText(QtGui.QApplication.translate("MainWindow", "0x00000000", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Bootstrap Memory Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Flash Programmer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Flash Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Serial Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Application Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Board Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Device Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Board Support Package (BSP) Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_binary_file.setText(QtGui.QApplication.translate("MainWindow", "&Open binary file...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_log.setText(QtGui.QApplication.translate("MainWindow", "View &log", None, QtGui.QApplication.UnicodeUTF8))

